default_language_version:
    python: python3.7
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: flake8
    - id: name-tests-test
    - id: pretty-format-json
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.0
    hooks:
    -   id: dockerfile_lint
    -   id: markdown-toc
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      name: Format changed Python files with Black
      language_version: python3.7
      args: [--line-length=79]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.740'
    hooks:
    - id: mypy
      name: Check static typing using mypy
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.2
    hooks:
    - id: python-check-blanket-noqa
      name: Check blanket noqa
    - id: python-use-type-annotations
      name: Type annotations not comments
