from typing import Dict

# STANDARD_TYPES
INT = "INT"
FLOAT = "FLOAT"
NUMERIC = "NUMERIC"
TEXT = "TEXT"
TIMESTAMP = "TIMESTAMP"
DATETIME_PANDAS = "DATETIME64[NS]"

# STANDARD_DATA_SOURCES
PANDAS = "PANDAS"

DIALECT_MAPPING: Dict[str, Dict[str, str]] = dict(
    PANDAS=dict(
        OBJECT=TEXT, DATETIME_PANDAS=TIMESTAMP, INT64=TEXT, FLOAT64=TEXT
    )
)

__all__ = ["DIALECT_MAPPING", "PANDAS"]
